name: rainforest_biz_project
description: ''
version: 0.1.0
author: somya.thatoi@teksystemsindia.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: rainforestbizproject
  parentArtefactID: somyathatoiteksystemsindiacomteam
  buildSystem: wheel
  author: null
  createdAt: '2024-08-11 18:14:11'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: somya.thatoi@teksystemsindia.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-11 18:14:11'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Account
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Opportunity
      outputs:
      - datasets/enriched_accounts
    subgraphs: []
    dependencies: {}
  pipelines/Sources_Walkthrough:
    name: Sources_Walkthrough
    description: ''
    author: somya.thatoi@teksystemsindia.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-13 13:23:27'
    datasets:
      inputs:
      - datasets/raw_product_line_a
      - datasets/raw_product_line_b
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/enriched_accounts:
    name: enriched_accounts
    description: ''
    author: somya.thatoi@teksystemsindia.com
    createdAt: '2024-08-11 19:03:29'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 14836
        datasetType: Database
        description: ''
        author: somya.thatoi@teksystemsindia.com
        createdAt: '2024-08-11 19:03:29'
  datasets/raw_product_line_a:
    name: raw_product_line_a
    description: ''
    author: somya.thatoi@teksystemsindia.com
    createdAt: '2024-08-13 13:45:08'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 14836
        datasetType: File
        description: ''
        author: somya.thatoi@teksystemsindia.com
        createdAt: '2024-08-13 13:45:08'
  datasets/raw_product_line_b:
    name: raw_product_line_b
    description: ''
    author: somya.thatoi@teksystemsindia.com
    createdAt: '2024-08-13 13:52:53'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 14836
        datasetType: File
        description: ''
        author: somya.thatoi@teksystemsindia.com
        createdAt: '2024-08-13 13:52:53'
templates: {}
jobs:
  jobs/daily_account:
    name: daily_account
    description: ''
    fabricUID: 14836
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: somya.thatoi@teksystemsindia.com
      onStart: true
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/enrich_accounts
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2024-08-11 19:12:36'
    author: somya.thatoi@teksystemsindia.com
    models: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-11 18:14:11'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-08-21T03:10:29.470705Z'
  name: plibMaven
  version: 8.0.31
  id: '841279943'
  createdAt: '2024-08-21T03:10:29.470668Z'
- type: plibPypi
  modifiedAt: '2024-08-21T03:10:29.470771Z'
  name: plibPypi
  version: 1.9.9
  id: '1379293636'
  createdAt: '2024-08-21T03:10:29.470761Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-08-11 18:09:24'
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2024-08-11 18:09:24'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-08-11 18:09:24'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
